### ISSUE TITLE
Run eslint and prettier on pre-commit the changes

### ISSUE THREAD

**Issue by Gaurav-Verma07** [Gaurav-Verma07/school-erp-system#24]
continue #15

**Comment by Laxmankohar** [comment]
I want to work on this issue under JWOC. Can you assign it yo me?

**Comment by Gaurav-Verma07** [comment]
When raising a PR, make sure to compare the changes with **task/eslint-pr-commit** branch and not **main** branch.

**Comment by Laxmankohar** [comment]
bro, could you please help me out. I am getting lockfileversion error.
![image](https://user-images.githubusercontent.com/73365025/221339907-8e2f5722-611e-4b67-bb06-3b3a914e4ffc.png)

**Comment by Laxmankohar** [comment]
@Gaurav-Verma07 bro, could you please check it?

![image](https://user-images.githubusercontent.com/73365025/221342584-aaae7770-7304-496a-90d5-0923ee923cad.png)
![image](https://user-images.githubusercontent.com/73365025/221342546-cc4435c1-1559-4df1-b96e-57d5d4f2a330.png)
![image](https://user-images.githubusercontent.com/73365025/221342548-fccb0dd4-95dd-4e3f-bc04-975690c29db0.png)

**Comment by Laxmankohar** [comment]
Bro, i am not able to understand the red color one. what does it mean?

![image](https://user-images.githubusercontent.com/73365025/221342636-4b5adda4-8f7e-486f-91dc-b936af824125.png)

**Comment by Gaurav-Verma07** [comment]
It seems a dependency issue that some have conflicting versions. 
Try refering this: [StackOverflow](https://stackoverflow.com/questions/33816824/getting-npm-err-code-epeerinvalid-on-npm-packages-global-install)

Try these steps:
1. Resistall latest npm version
2. Delete `node modules` and `package-lock.json`
3. Update dependencies using `npm update -g`
4. Reinstall dependencies-  `npm install`

**Comment by Laxmankohar** [comment]
> It seems a dependency issue that some have conflicting versions. Try refering this: [StackOverflow](https://stackoverflow.com/questions/33816824/getting-npm-err-code-epeerinvalid-on-npm-packages-global-install)
> 
> Try these steps:
> 
> 1. Resistall latest npm version
> 2. Delete `node modules` and `package-lock.json`
> 3. Update dependencies using `npm update -g`
> 4. Reinstall dependencies-  `npm install`

Done...but what the  red one  deleted: README.md and other mean?

**Comment by Gaurav-Verma07** [comment]
The red One. It doesn't seems to be an error, its a message that those deleted files are untracked.
Did you deleted those files???

**Comment by Laxmankohar** [comment]
> The red One. It doesn't seems to be an error, its a message that those deleted files are untracked. Did you deleted those files???

No. all the files are available in the folder

**Comment by Laxmankohar** [comment]
what should i do next?
should i make pull request?

**Comment by Gaurav-Verma07** [comment]
Yeah, raise a PR and compare the changes with **task/eslint-pr-commi**t branch.
If any error persists, I'll resolve it.

**Comment by Gaurav-Verma07** [comment]
Show me your **source control panel** of VS code.

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/221355694-77f91112-43aa-4315-9919-f0b2417f2150.png)
![image](https://user-images.githubusercontent.com/73365025/221355720-b5bfc1eb-d6f2-4e74-b7fd-c35f984bd35c.png)

**Comment by Gaurav-Verma07** [comment]
That's strange.
 `server/admin/src` admin is in server directory and deleted too. Something clearly messed up here.
You please push the changes, I'll see.

**Comment by Laxmankohar** [comment]
Should i fetch all the branch in task?eslint-pr-commit? right now , iam in task/eslint-pr-commit.
![image](https://user-images.githubusercontent.com/73365025/221356669-04373f69-5e2b-41dd-8b3f-3c233c80cd58.png)

**Comment by Gaurav-Verma07** [comment]
No, just push from here and in browser while raising a PR select `task/eslint-pr-commit` branch for comparing otherwise there'd be lot of merge conflicts.
![image](https://user-images.githubusercontent.com/63046396/221357054-c4ddb196-d9b1-47c4-9dea-e57db47c1d09.png)

**Comment by Laxmankohar** [comment]
Bro, I have made a pr . check it.

**Comment by Gaurav-Verma07** [comment]
Resolved with PR #26
